# Generated by Django 3.0.7 on 2020-07-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20200710_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.Order'),
        ),
    ]
