# Generated by Django 3.0.7 on 2020-07-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_customerorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='product',
        ),
    ]
