# Generated by Django 3.0.7 on 2020-07-12 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_remove_customerorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.Product'),
        ),
    ]
