# Generated by Django 3.0.7 on 2020-07-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_customerorder_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
    ]
