# Generated by Django 3.0.7 on 2020-07-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_remove_customerorder_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
